# 请求数据
resp:
  url: https://shop.laiyangni.com/api/lyn/wechat/home/shopInfo/v2
  params:
    sign: "hP4OmmDtvFzjxryRNjVnIQ=="
    data: "Sg2zSzc1Gl+o/VhUi2CzQUcCP7gVpDM/V+9cRbmWhC1U93A/vgQW/KgZexwCgYXvH5ck454hFSmmTv7BlSkrTWm0l3lpoTzZiavAZXiIfpcbik5DFAEfgjUYDScFld/v"
# 各种信息的路径
path:
  # 用户数据
  dat_file: config/usr.dat
# 设定定时请求参数
setInterval:
  # 请求间隔时间
  # delta_time: 5*60
  delta_time: 3
  # 自动唤醒时间
  wake_time: 7:30:0
  # 自动休眠时间
  sleep_time: 18:0:0
# 商铺筛选参数
constraint:
  # 特别关心
  likes: 27572,25235,27944,27946,25235,25260
  # 商家距离限定
  max_distance: 2.5e3
